### ISSUE TITLE
About pep8 and more testing ?

### ISSUE THREAD

**Issue by gdchamal** [tBaxter/vobject#11]
Would you mind if I make a pull request for a whole pep8 formatting on your fork ? 
It will be important change as original code base is really old and have it's own code style.

It's not so important of course, but it will make my linter feel really less stressed ;)

I have also idea to had more testing around vcard parsing features (2.1, 3.0, 4.0) has it's currently my focus (I do not have current usage of ical). That will be another PR than a formatting one, of course.

And may thanks for your work. I can't find a better vcard package in python world except this old vobject one that disappear from pypi, and as py3 is mandatory for me, it fit perfectly when I found your work.

**Comment by tBaxter** [comment]
Send the PR. Worst case I don't merge it, but most likely I would.

**Comment by tBaxter** [comment]
@gdchamal if you're still interested, please submit that PR to https://github.com/tBaxter/python-card-me

Thanks

**Comment by gdchamal** [comment]
yes still interested in this project but didn't get enough time to continue my pep8 adventure ;)

I'll follow your new repository, thanks
