### ISSUE TITLE
'python-dateutil == 2.4.0'

### ISSUE THREAD

**Issue by DamienCassou** [tBaxter/vobject#12]
Do you really need dateutil to be at exactly 2.4.0 or can it be a little different? My distribution and pypi have 2.4.2.

https://github.com/tBaxter/vobject/blob/0.8.3/setup.py#L59

**Comment by pypingou** [comment]
You can likely be 2.4.2, the readme just mentions version 2 or above.

**Comment by DamienCassou** [comment]
What about fixing it in the setup.py then? Otherwise, I have to write patch for my distribution which uses the setup.py to fetch the dependencies.

**Comment by tBaxter** [comment]
2.4.2 creates a test failure in python 3: https://travis-ci.org/tBaxter/vobject/jobs/88801271

**Comment by tBaxter** [comment]
Moving.

**Comment by pypingou** [comment]
An info on moving to what/where would have been nice.

Might be worth adding to the README as well

**Comment by tBaxter** [comment]
Sorry... moved to: https://github.com/tBaxter/python-card-me
