### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by pypingou** [tBaxter/vobject#15]
The version on pypi is 0.8.1: https://pypi.python.org/pypi/vobject

The repo has only 1 tag: 0.8.3: https://github.com/tBaxter/vobject/releases

The version in the setup.py is 0.8.5: https://github.com/tBaxter/vobject/blob/master/setup.py#L50

So looking at this it seems a few releases have been made but only one got tagged. Would it be possible to tag them and push them to github?

Thanks!

**Comment by tBaxter** [comment]
Thanks. I cut a Github 0.8.5 release. The version on pypi ain't me. I'm still not entirely sure what's going on with the "official" branch.

**Comment by pypingou** [comment]
Thanks for the tag.

Do you thikn you could find back the commits corresponding to 0.8.2 and 0.8.4 to tag them as well?

**Comment by tBaxter** [comment]
Probably could, but I'm not really sure how much value there is in it?
What's your thinking?

**Comment by pypingou** [comment]
Just keeping track of what the releases are :)
