### ISSUE TITLE
Breaks both khard and pycarddav

### ISSUE THREAD

**Issue by DamienCassou** [tBaxter/vobject#16]
It seems that your version of vobject breaks both pycarddav and khard. It might be ok, but I just wanted to let you know. Upstream issues are https://github.com/scheibler/khard/issues/30 and https://github.com/geier/pycarddav/issues/119

**Comment by tBaxter** [comment]
In my opinion, those libraries need to update their own very old code.

**Comment by DamienCassou** [comment]
Do you have any guideline regarding what has changed? Also, I read you didn't want to maintain this package in the long term. Did you change your mind? Does it make sense to update client packages to work with a fork if it is not maintained?

**Comment by tBaxter** [comment]
My hope is that a more engaged maintainer will want to take it over. Until then, I'll keep doing it. 

I think those libraries are making some very old and dangerous assumptions about starting out in the ascii space and should update their code to only encode if encoding is needed, or just fail if it's not encoded (as it always should be). But that's just an off-the-cuff opinion. I have not dug into their source.

**Comment by DamienCassou** [comment]
Thank you.
