### ISSUE TITLE
dtstart is a datetime on vobject for python2 but a string on your vobject for python3

### ISSUE THREAD

**Issue by Niols** [tBaxter/vobject#7]
Haha, finally!

I tried to use your fork of vobject, because it supports python3. Actually, it supports python3 pretty well.
I've still noticed one little difference between the behaviour of vobject for python2 and yours.

I'm using this vobject as a dependance for caldav, which is supposed to support python3. But the DTSTART field is a **datetime** on python2 and only a **string** representing it on python3. I have this little test code:

    #!/usr/bin/python
    # -*- coding: utf-8 -*-
    
    from __future__ import unicode_literals
    import caldav
    
    url = 'https://username:password@caldav.example.com/'
    davclient = caldav.DAVClient(url)
    print('davclient', type(davclient))
    
    calendar = davclient.principal().calendars()[0]
    print('calendar', type(calendar))
    
    event = calendar.events()[0]
    print('event', type(event))
    print('event.instance', type(event.instance))
    print('event.instance.vevent', type(event.instance.vevent))
    print('event.instance.vevent.dtstart', type(event.instance.vevent.dtstart))
    print('event.instance.vevent.dtstart.value', type(event.instance.vevent.dtstart.value))
    print('event.instance.vevent.dtstart.value', event.instance.vevent.dtstart.valueRepr)

On python2, this outputs:

    (u'davclient', <type 'instance'>)
    (u'calendar', <class 'caldav.objects.Calendar'>)
    (u'event', <class 'caldav.objects.Event'>)
    (u'event.instance', <class 'vobject.base.Component'>)
    (u'event.instance.vevent', <class 'vobject.icalendar.RecurringComponent'>)
    (u'event.instance.vevent.dtstart', <class 'vobject.base.ContentLine'>)
    (u'event.instance.vevent.dtstart.value', <type 'datetime.date'>)
    (u'event.instance.vevent.dtstart.value', datetime.date(2015, 4, 28))

and on python3:

    davclient <class 'caldav.davclient.DAVClient'>
    calendar <class 'caldav.objects.Calendar'>
    event <class 'caldav.objects.Event'>
    event.instance <class 'vobject.base.Component'>
    event.instance.vevent <class 'vobject.base.Component'>
    event.instance.vevent.dtstart <class 'vobject.base.ContentLine'>
    event.instance.vevent.dtstart.value <class 'str'>
    event.instance.vevent.dtstart.value 20150505

Note: this script supposes that you have calendars, and that none of them is empty. It can fail otherwise.

Here are my (shortened) `pipN show vobject`:

    pip2 show vobject
    ---
    Version: 0.6.6
    Author: Jeffrey Harris

    pip3 show vobject
    ---
    Version: 0.8.2
    Author: Jeffrey Harris, Tim Baxter

Sorry, that's a lot of code. I'll try to be as available as possible.

Non-related question: is this repo intended to become the reference for vobject for python3?

**Comment by tBaxter** [comment]
Niols, are you still seeing this problem?

**Comment by tBaxter** [comment]
@Niols if you are still seeing this, please log an issue on https://github.com/tBaxter/python-card-me

Thanks
