### ISSUE TITLE
"ics_diff foo bar" and "ics_diff bar foo" can show different number of changes

### ISSUE THREAD

**Issue by normanr** [tBaxter/vobject#8]
If I create two files with slightly overlapping series of events:

foo: a b c
bar: b c d
(where a b c d are events in chronologically increasing order)

and then "ics_diff foo bar" and "ics_diff bar foo" show different number of changes.

This seems to be because processComponentLists doesn't process the end of rightList once leftList is processed (leaving some events unaccounted for)

**Comment by tBaxter** [comment]
I'm not sure I'm following. Do you have a fix in mind you could submit a PR for?

**Comment by tBaxter** [comment]
@normanr if you're still seeing this, please log a fresh issue (or better, a PR) to https://github.com/tBaxter/python-card-me

Thanks!
