### ISSUE TITLE
python2: vobject.base.VObjectError: 'No behavior found named VCALENDAR'

### ISSUE THREAD

**Issue by akriegisch** [tBaxter/vobject#9]
python2 requires the following patch to work (I guess this is -- at least partly -- in pull request #6):
<pre>
--- vobject/__init__.py.orig    2015-08-26 15:03:18.000000000 +0200
+++ vobject/__init__.py 2015-08-26 15:00:01.000000000 +0200
@@ -76,6 +76,7 @@

 """

+import base, icalendar, vcard
 from .base import newFromBehavior, readOne, readComponents

</pre>

**Comment by tBaxter** [comment]
PR6 has been merged. I'm not seeing this anymore. Are you?

**Comment by akriegisch** [comment]
partly: fixed for vcalendar but not for vcard:
<pre>
Python 2.7.3 (default, Mar 13 2014, 11:03:55)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import vobject
>>> vobject.iCalendar()
&lt;VCALENDAR| []&gt;
>>> vobject.vCard()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "vobject/__init__.py", line 94, in vCard
    return newFromBehavior('vcard', '3.0')
  File "vobject/base.py", line 1147, in newFromBehavior
    raise VObjectError("No behavior found named %s" % name)
vobject.base.VObjectError: 'No behavior found named VCARD'
</pre>

to completely fix this, import vcard in __init__ too (or make that part conditional for py2 only).

**Comment by tBaxter** [comment]
Gotcha. Try it now.

**Comment by akriegisch** [comment]
(sorry for the delay in my reply)
Thank you very much! The issue is fixed now; closing! ;-)
